### ISSUE TITLE
Plugin is not compatible with WPML

### ISSUE THREAD

**Issue by keanekwa** [woothemes/testimonials#65]
Hi,

After I translated the testimonials in the plugin on my website, the testimonials section on the translated website was empty. I could only see the testimonials on the English version of my website.

Can you help me fix this issue?

Thanks,
Keane

**Comment by jameskoster** [comment]
I'm not sure what you mean by 'empty'. You mean the translation wasn't applied or something else?

Anyway, GitHub isn't the place to post for support so I'm closing this issue. Please post on the wordpress.org forums or submit a feature request on our ideasboard.

Thanks.
