### ISSUE TITLE
Add screenshot of plugin working

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/testimonials#72]
It would be nice to see an example of the plugin working in the plugin repository

<img width="971" alt="screen shot 2015-11-25 at 4 05 18 pm" src="https://cloud.githubusercontent.com/assets/2293077/11409494/63c41690-938e-11e5-9bcf-1675ad0c9b23.png">

**Comment by BurlesonBrad** [comment]
https://pressily.com/testimonials/ <--- looks like poo & will probably be deleted soon, but nonetheless....

@DustinHartzler along w/ #74 , Snag some screenshots here and do with them whatever you'd like!

If I'm gonna use pics of folks, I reckon it'd be polite if I tagged 'em:
@nicoleckohler https://pressily.com/testimonial/nicole-kohler/
@roykho https://pressily.com/testimonial/roy-ho/
@mikejolley https://pressily.com/testimonial/great-ghostbusting-skills/
@slash1andy https://pressily.com/testimonial/i-love-these-bowties/

https://pressily.com/testimonial-page/
Quick Testimonial Page using a few different quick short codes.  
Sidebar widget looks like poo though. 😞 

WP 4.7 SF 2.1.6

**Comment by BurlesonBrad** [comment]
and a nice pic of the admin area of the shiny new 4.7
![wt-admin](https://cloud.githubusercontent.com/assets/6208757/20947246/f1366604-bbd3-11e6-9661-bbe220005a09.png)

**Comment by nicoleckohler** [comment]
Please do not use mine/include me there - thank you :)

**Comment by roykho** [comment]
@BurlesonBrad same - Please do not use mine/include me there - thank you :)
